import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const id = process.argv[2] ?? '';
if (!/^[a-z][a-z0-9-]{1,40}$/.test(id)) {
  throw new Error(
    'Use a lowercase tool ID, for example: npm run new-tool -- case-review',
  );
}
if (id === 'feature-flags' || id === 'refunds') {
  throw new Error(
    `The ${id} tool is reserved and is not generated by this command.`,
  );
}

const root = process.cwd();
const toolRoot = resolve(root, 'tools', id);
const fs = await import('node:fs/promises');
if (
  await fs.stat(toolRoot).then(
    () => true,
    () => false,
  )
) {
  throw new Error(`tools/${id} already exists`);
}
const safeName = id
  .replaceAll('-', ' ')
  .replace(/\b\w/g, (letter) => letter.toUpperCase());
const permission = `${id}.read`;
await mkdir(resolve(toolRoot, 'src'), { recursive: true });
await mkdir(resolve(toolRoot, 'migrations'), { recursive: true });
await mkdir(resolve(toolRoot, 'tests'), { recursive: true });
await mkdir(resolve(toolRoot, 'pages'), { recursive: true });
await mkdir(resolve(toolRoot, 'runbooks'), { recursive: true });

await writeFile(
  resolve(toolRoot, 'package.json'),
  JSON.stringify(
    {
      name: `@internal-tools/${id}`,
      version: '0.1.0',
      private: true,
      type: 'module',
      main: './src/index.ts',
      types: './src/index.ts',
      dependencies: {
        '@internal-tools/foundation': '*',
        '@internal-tools/testing': '*',
      },
    },
    null,
    2,
  ) + '\n',
);
await writeFile(
  resolve(toolRoot, 'tsconfig.json'),
  JSON.stringify(
    {
      extends: '../../tsconfig.base.json',
      compilerOptions: { rootDir: 'src', outDir: 'dist' },
      references: [
        { path: '../../packages/foundation' },
        { path: '../../packages/testing' },
      ],
      include: ['src/**/*.ts'],
    },
    null,
    2,
  ) + '\n',
);
await writeFile(
  resolve(toolRoot, 'src/index.ts'),
  `import { defineTool } from '@internal-tools/foundation';

export const ${id.replaceAll('-', '_')}Tool = defineTool({
  id: '${id}',
  name: '${safeName}',
  owner: 'tool-owner@company.example',
  dataClass: 'internal',
  roles: {
    agent: { idpGroup: '${id}-agent' },
    auditor: { idpGroup: 'auditor' },
  },
  permissions: {
    '${permission}': ['agent', 'auditor'],
  },
});
`,
);
await writeFile(
  resolve(toolRoot, 'src/routes.ts'),
  `import { defineRoute } from '@internal-tools/foundation';

export const ${id.replaceAll('-', '_')}Routes = [
  defineRoute({
    method: 'GET',
    path: '/api/tools/${id}',
    permission: '${permission}',
    handler: () => ({ tool: '${id}', status: 'ready' }),
  }),
];
`,
);
await writeFile(
  resolve(toolRoot, 'migrations/001_init.sql'),
  `CREATE SCHEMA IF NOT EXISTS ${id.replaceAll('-', '_')};

CREATE TABLE IF NOT EXISTS ${id.replaceAll('-', '_')}.records (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now()
);
`,
);
await writeFile(
  resolve(toolRoot, 'src/page.tsx'),
  `export default function ${safeName.replaceAll(' ', '')}Page() {
  return <section><p>INTERNAL TOOL</p><h1>${safeName}</h1><p>Replace this page with the reviewed workflow.</p></section>;
}
`,
);
await writeFile(
  resolve(toolRoot, 'tests/registry.test.ts'),
  `import { describe, expect, it } from 'vitest';
import { ${id.replaceAll('-', '_')}Tool } from '../src/index.js';

describe('${safeName} registry', () => {
  it('declares a read permission for the tool', () => {
    expect(${id.replaceAll('-', '_')}Tool.permissions['${permission}']).toContain('agent');
  });
});
`,
);
await writeFile(
  resolve(toolRoot, 'runbooks/README.md'),
  `# ${safeName} runbook

Describe the main alert, how to inspect the records, and safe recovery steps.
`,
);

async function insertMarker(file: string, marker: string, value: string) {
  const path = resolve(root, file);
  const source = await readFile(path, 'utf8');
  if (!source.includes(marker))
    throw new Error(`Integration marker is missing from ${file}`);
  await writeFile(path, source.replace(marker, `${value}\n${marker}`));
}

const symbol = id.replaceAll('-', '_');
const pageSource = `export default function ${safeName.replaceAll(' ', '')}Page() {
  return <section><p>INTERNAL TOOL</p><h1>${safeName}</h1><p>Replace this page with the reviewed workflow.</p></section>;
}
`;
await insertMarker(
  'apps/api/src/tool-registry.ts',
  '// <DEVIN-TOOL-IMPORTS>',
  `import { ${symbol}Tool } from '@internal-tools/${id}';`,
);
await insertMarker(
  'apps/api/src/tool-registry.ts',
  '// <DEVIN-TOOL-REGISTRY>',
  `${symbol}Tool,`,
);
await insertMarker(
  'apps/api/src/server.ts',
  '// <DEVIN-TOOL-PERMISSIONS>',
  `'GET /api/tools/${id}': '${permission}',`,
);
await insertMarker(
  'apps/api/src/server.ts',
  '// <DEVIN-TOOL-ROUTES>',
  `server.get('/api/tools/${id}', async (request, reply) => {
  const tool = toolRegistry.find((entry) => entry.id === '${id}')!;
  const user = await requirePermission(request as ApiRequest, reply, '${permission}', tool);
  if (!user) return;
  return { tool: '${id}', status: 'ready' };
});`,
);
await insertMarker(
  'apps/web/src/App.tsx',
  '// <DEVIN-TOOL-IMPORTS>',
  `import ${safeName.replaceAll(' ', '')}Page from './generated/${id}';`,
);
await mkdir(resolve(root, 'apps/web/src/generated'), { recursive: true });
await writeFile(
  resolve(root, 'apps/web/src/generated', `${id}.tsx`),
  pageSource,
);
await insertMarker(
  'apps/web/src/App.tsx',
  '// <DEVIN-TOOL-NAV>',
  `{ to: '/tools/${id}', label: '${safeName}', icon: CircleHelp },`,
);
await insertMarker(
  'apps/web/src/App.tsx',
  '{/* <DEVIN-TOOL-ROUTES> */}',
  `<Route path="/tools/${id}" element={<${safeName.replaceAll(' ', '')}Page />} />`,
);

const rootConfigPath = resolve(root, 'tsconfig.json');
const rootConfig = JSON.parse(await readFile(rootConfigPath, 'utf8')) as {
  references: Array<{ path: string }>;
};
if (
  !rootConfig.references.some((reference) => reference.path === `./tools/${id}`)
) {
  rootConfig.references.push({ path: `./tools/${id}` });
  await writeFile(rootConfigPath, JSON.stringify(rootConfig, null, 2) + '\n');
}

const apiPackagePath = resolve(root, 'apps/api/package.json');
const apiPackage = JSON.parse(await readFile(apiPackagePath, 'utf8')) as {
  dependencies: Record<string, string>;
};
apiPackage.dependencies[`@internal-tools/${id}`] = '*';
await writeFile(apiPackagePath, JSON.stringify(apiPackage, null, 2) + '\n');

const apiConfigPath = resolve(root, 'apps/api/tsconfig.json');
const apiConfig = JSON.parse(await readFile(apiConfigPath, 'utf8')) as {
  references: Array<{ path: string }>;
};
if (
  !apiConfig.references.some(
    (reference) => reference.path === `../../tools/${id}`,
  )
) {
  apiConfig.references.push({ path: `../../tools/${id}` });
  await writeFile(apiConfigPath, JSON.stringify(apiConfig, null, 2) + '\n');
}

console.log(`Created tools/${id} and registered its API and web entry points.`);
